### ISSUE TITLE
v0 android and web launch

### ISSUE THREAD

**Issue by xcolwell** [urnetwork/server#97]
This will be a soft launch, where we won't do any press. The goal of this launch is to get the new Android app out, and to switch to the new website and brand.

~~Launch target: **Friday October 4**~~
App store submissions: Wed October 9
Website launch: Friday October 11

P0 issues blocking app store submission have been separated into https://github.com/bringyour/bringyour/issues/127
Non-blocking issues added here: https://github.com/bringyour/bringyour/issues/132

Items to complete below. Cross out items if they are no longer in the launch scope.

### Android

- [x] Play store subscription for supporter
- [x] Tap on location from list doesn't appear to connect correctly
- [x] Location list doesn't appear to retry correctly when api call fails
- [x] Screen size issues: test large, high DPI screens like S24 Ultra
- [x] API: https://github.com/bringyour/bringyour/issues/44
- [x] API: https://github.com/bringyour/bringyour/issues/34
- [x] Filter locations does not show regions or cities when searching
- [x]  Filter locations search box should have an easy clear "x" (android `app:endIconMode="clear_text"`) 
- [x] Filter UI polish: best match section for match distance <= 1; refresh button for the failure case only
- [x] resource translations to target languages (use Gemini or Claude)
- [x] Circle SDK style and testing
- [x] Circle Transfer Funds page
- [x] Wire up the settings page
- [x] Update profile page needs to be connected to API endpoint
- [x] Connect button success circles not persisting when navigating away
- [x] Remove wallet UI
- [ ] Ensure Saga working on Mainnet (currently forcing wallet be connected to Testnet)
- [x] Wallet estimate payout (or show amount of data currently processed in this cycle)
- [x] Search by urid
- [x] Login with google - allow switching accounts
- [x] prompt to rate (should be closed by https://github.com/bringyour/android/pull/118, needs to be tested through an internal release)
- [x] Pull user refer code for referral overlay
- [x] Polygon address validation issues
- [x] Fetching earnings on Account page hanging on internal release 

### Web

- [ ] Connect button - new style, replace web app and questions on login with app downloads and waitlist sign ups.
- [ ] What's my IP page
- [x] Blog navigation/subsections
- [ ] Remove filler content and put in real content: Allison's piece and first 18O piece
- [x] Footer cleanup with feedback (Nolt), support (Intercom), and docs (Gitbook) pages styled and set up

### Network

- [x] ~~Merge new gvisor ip implementation. If this isn't a performance improvement or ready to go, we can cut this. Expecting to see better upload and download speeds.~~ Update: skip the gvisor update this release. Instead merge performance fixes to ip and transfer.
- [ ] Add new community geos and make sure community geos are working correctly: https://github.com/bringyour/bringyour/issues/98
- [x] Fix free mode and subsidy payout: https://github.com/bringyour/bringyour/issues/101
- [ ] Provider ranking and bonus: https://github.com/bringyour/bringyour/issues/112
